// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnw4guO3Uvct9O4ALqnOR6oh0yoqsR9f4',
    appId: '1:893989558934:web:f2fce35aac95c5f38000b7',
    messagingSenderId: '893989558934',
    projectId: 'colleague-app-95c37',
    authDomain: 'colleague-app-95c37.firebaseapp.com',
    storageBucket: 'colleague-app-95c37.appspot.com',
    measurementId: 'G-6S78VMRQD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGxozc250we7QFMq3jzxyoE3GU3yWMXBo',
    appId: '1:893989558934:android:1bab90891bac514a8000b7',
    messagingSenderId: '893989558934',
    projectId: 'colleague-app-95c37',
    storageBucket: 'colleague-app-95c37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC8yH_naByjAFy_ZsSeBjEiaTSS4jIdag',
    appId: '1:893989558934:ios:6f47efc7a6a6f5be8000b7',
    messagingSenderId: '893989558934',
    projectId: 'colleague-app-95c37',
    storageBucket: 'colleague-app-95c37.appspot.com',
    iosBundleId: 'com.example.collegeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC8yH_naByjAFy_ZsSeBjEiaTSS4jIdag',
    appId: '1:893989558934:ios:f56e401e85e49a878000b7',
    messagingSenderId: '893989558934',
    projectId: 'colleague-app-95c37',
    storageBucket: 'colleague-app-95c37.appspot.com',
    iosBundleId: 'com.example.collegeApp.RunnerTests',
  );
}
